package com.leviathanledger.leviathan.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * LexTracker Integrity Engine: Document Entity
 * Purpose: Acts as the "Vault Slot" for legal evidence AND generated legal documents
 * with immutable hashing and full audit trail.
 */
@Entity
@Table(name = "documents", indexes = {
        @Index(name = "idx_legal_case_id", columnList = "legal_case_id"),
        @Index(name = "idx_document_category", columnList = "document_category"),
        @Index(name = "idx_document_type", columnList = "document_type")
})
public class Document {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String fileName;

    private String fileType;

    @Column(nullable = false)
    private String filePath;

    @Column(nullable = false, unique = true)
    private String fileHash; // The SHA-256 Digital Fingerprint

    @Column(name = "source_origin", length = 500)
    private String sourceOrigin; // Captured from the physical world origin or generation context

    // NEW: Distinguish between evidence and generated legal documents
    @Column(name = "document_category", nullable = false)
    private String documentCategory; // "EVIDENCE" or "LEGAL_DOCUMENT"

    // NEW: Specific document type for generated legal documents
    @Column(name = "document_type")
    private String documentType; // "NOTICE_OF_INTENTION", "SUMMONS_TO_FILE_DEFENCE", etc.

    // NEW: Document size in bytes for tracking
    @Column(name = "file_size")
    private Long fileSize;

    // NEW: Generation context (which endpoint generated it)
    @Column(name = "generation_context")
    private String generationContext;

    @Column(nullable = false)
    private LocalDateTime uploadedAt;

    @Column(name = "uploaded_by", nullable = false)
    private String uploadedBy;

    @Column(nullable = false)
    private Integer version = 1;

    @Column(nullable = false)
    private boolean archived = false;

    // CRITICAL FIX: Prevent lazy proxy serialization error
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "legal_case_id")
    @JsonIgnore
    private LegalCase legalCase;

    @PrePersist
    protected void onCreate() {
        this.uploadedAt = LocalDateTime.now();
        if (this.version == null) {
            this.version = 1;
        }
        if (this.documentCategory == null) {
            this.documentCategory = "EVIDENCE"; // Default to evidence
        }
    }

    public Document() {}

    /**
     * Constructor for evidence documents
     */
    public Document(String fileName, String fileType, String filePath, String fileHash,
                    String sourceOrigin, String uploadedBy, LegalCase legalCase) {
        this.fileName = fileName;
        this.fileType = fileType;
        this.filePath = filePath;
        this.fileHash = fileHash;
        this.sourceOrigin = sourceOrigin;
        this.uploadedBy = uploadedBy;
        this.legalCase = legalCase;
        this.documentCategory = "EVIDENCE";
    }

    /**
     * Constructor for generated legal documents
     */
    public Document(String fileName, String fileType, String filePath, String fileHash,
                    String documentType, String uploadedBy, LegalCase legalCase, long fileSize) {
        this.fileName = fileName;
        this.fileType = fileType;
        this.filePath = filePath;
        this.fileHash = fileHash;
        this.documentType = documentType;
        this.uploadedBy = uploadedBy;
        this.legalCase = legalCase;
        this.fileSize = fileSize;
        this.documentCategory = "LEGAL_DOCUMENT";
        this.sourceOrigin = "Generated by LexTracker Automated Secretary";
        this.generationContext = "PDF_GENERATOR";
    }

    // --- GETTERS AND SETTERS ---

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getFileName() { return fileName; }
    public void setFileName(String fileName) { this.fileName = fileName; }

    public String getFileType() { return fileType; }
    public void setFileType(String fileType) { this.fileType = fileType; }

    public String getFilePath() { return filePath; }
    public void setFilePath(String filePath) { this.filePath = filePath; }

    public String getFileHash() { return fileHash; }
    public void setFileHash(String fileHash) { this.fileHash = fileHash; }

    public String getSourceOrigin() { return sourceOrigin; }
    public void setSourceOrigin(String sourceOrigin) { this.sourceOrigin = sourceOrigin; }

    public String getDocumentCategory() { return documentCategory; }
    public void setDocumentCategory(String documentCategory) { this.documentCategory = documentCategory; }

    public String getDocumentType() { return documentType; }
    public void setDocumentType(String documentType) { this.documentType = documentType; }

    public Long getFileSize() { return fileSize; }
    public void setFileSize(Long fileSize) { this.fileSize = fileSize; }

    public String getGenerationContext() { return generationContext; }
    public void setGenerationContext(String generationContext) { this.generationContext = generationContext; }

    public LocalDateTime getUploadedAt() { return uploadedAt; }
    public void setUploadedAt(LocalDateTime uploadedAt) { this.uploadedAt = uploadedAt; }

    public String getUploadedBy() { return uploadedBy; }
    public void setUploadedBy(String uploadedBy) { this.uploadedBy = uploadedBy; }

    public Integer getVersion() { return version; }
    public void setVersion(Integer version) { this.version = version; }

    public boolean isArchived() { return archived; }
    public void setArchived(boolean archived) { this.archived = archived; }

    public LegalCase getLegalCase() { return legalCase; }
    public void setLegalCase(LegalCase legalCase) { this.legalCase = legalCase; }

    /**
     * Helper method to get formatted file size for display
     */
    public String getFormattedFileSize() {
        if (fileSize == null) return "Unknown";
        if (fileSize < 1024) return fileSize + " B";
        if (fileSize < 1024 * 1024) return String.format("%.1f KB", fileSize / 1024.0);
        return String.format("%.1f MB", fileSize / (1024.0 * 1024.0));
    }

    /**
     * Helper method to get document type display name
     */
    public String getDisplayDocumentType() {
        if ("EVIDENCE".equals(documentCategory)) {
            return "Evidence Document";
        }
        return switch (documentType) {
            case "NOTICE_OF_INTENTION" -> "Notice of Intention to Sue";
            case "SUMMONS_TO_FILE_DEFENCE" -> "Summons to File Defence";
            case "ORIGINATING_SUMMONS" -> "Originating Summons";
            case "SUMMONS_FOR_DIRECTIONS" -> "Summons for Directions";
            case "EXTENSION_OF_TIME" -> "Application for Extension of Time";
            default -> documentType != null ? documentType.replace("_", " ") : "Legal Document";
        };
    }

    /**
     * Helper method to get upload timestamp formatted
     */
    public String getFormattedUploadedAt() {
        if (uploadedAt == null) return "Unknown";
        return uploadedAt.format(DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm"));
    }
}