package com.leviathanledger.leviathan.util;

import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

/**
 * Leviathan Ledger: Legal Template Utility
 * Purpose: Standardizing the Ugandan Judiciary format across all generated PDFs.
 */
public class LegalTemplateUtil {

    /**
     * Adds the mandatory Republic of Uganda header.
     */
    public static void addUgandanHeader(Document document) {
        document.add(new Paragraph("THE REPUBLIC OF UGANDA")
                .setTextAlignment(TextAlignment.CENTER)
                .setBold()
                .setFontSize(14)
                .setMarginBottom(2));

        // Visual separator often found in High Court documents
        document.add(new Paragraph("_________________________________")
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(15));
    }

    /**
     * Adds the Court and Division information.
     */
    public static void addCourtInfo(Document document, String courtLocation, String division) {
        String location = (courtLocation != null && !courtLocation.trim().isEmpty())
                ? courtLocation.toUpperCase()
                : "KAMPALA";

        document.add(new Paragraph("IN THE HIGH COURT OF UGANDA AT " + location)
                .setTextAlignment(TextAlignment.CENTER)
                .setBold()
                .setFontSize(11));

        if (division != null && !division.trim().isEmpty()) {
            document.add(new Paragraph("(" + division.toUpperCase() + " DIVISION)")
                    .setTextAlignment(TextAlignment.CENTER)
                    .setItalic()
                    .setFontSize(10));
        }
        document.add(new Paragraph("\n"));
    }

    /**
     * Adds the LexTracker Digital Stamp (The "Peace of Mind" Seal).
     * This proves the document was generated by your secure system.
     */
    public static void addDigitalSignature(Document document, String caseNumber) {
        document.add(new Paragraph("\n\n\n")); // Spacer

        document.add(new Paragraph("-----------------------------------------------------------------------")
                .setTextAlignment(TextAlignment.CENTER)
                .setFontSize(8));

        document.add(new Paragraph("CERTIFIED BY LEXTRACKER UGANDA INTEGRITY ENGINE")
                .setBold()
                .setFontSize(9)
                .setTextAlignment(TextAlignment.CENTER));

        document.add(new Paragraph("This is an electronically generated legal document. Case Ref: " + (caseNumber != null ? caseNumber : "NOT ASSIGNED"))
                .setFontSize(8)
                .setItalic()
                .setTextAlignment(TextAlignment.CENTER));

        document.add(new Paragraph("Verified for use in the Courts of Judicature of Uganda.")
                .setFontSize(7)
                .setTextAlignment(TextAlignment.CENTER));
    }

    /**
     * Helper to add Party identifiers (Plaintiff vs Defendant)
     */
    public static void addParties(Document document, String plaintiff, String defendant) {
        if (plaintiff != null && !plaintiff.trim().isEmpty()) {
            document.add(new Paragraph(plaintiff.toUpperCase() + " :::::::::::::::::::::::::::::::::::::: PLAINTIFF")
                    .setFontSize(10));
        } else {
            document.add(new Paragraph("THE PLAINTIFF :::::::::::::::::::::::::::::::::::::: PLAINTIFF")
                    .setFontSize(10));
        }

        document.add(new Paragraph("VERSUS")
                .setTextAlignment(TextAlignment.CENTER)
                .setBold()
                .setFontSize(10));

        if (defendant != null && !defendant.trim().isEmpty()) {
            document.add(new Paragraph(defendant.toUpperCase() + " :::::::::::::::::::::::::::::::::::::: DEFENDANT")
                    .setFontSize(10));
        } else {
            document.add(new Paragraph("THE DEFENDANT :::::::::::::::::::::::::::::::::::::: DEFENDANT")
                    .setFontSize(10));
        }

        document.add(new Paragraph("\n"));
    }
}